services:
  - type: web
    name: podcast-summarizer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p content
    startCommand: streamlit run podcast_frontend.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
    plan: starter
    healthCheckPath: /
    autoDeploy: true 